"""
Generate reference for all the different kinds of public API that we expose,
like regular Python imports, template tags, settings, Django URLs, etc.

All pages are generated inside `docs/reference/`.

Generation flow:
1. For each section, like `commands`, we look up the corresponding template
   named `reference_<section>.md`, e.g. `docs/templates/reference_commands.md`.

   This template contains the "preface" or text that will be rendered BEFORE
   the auto-generated docs.

2. For each section, we try to import it same way as the user would. And for each
   section we do filtering and post-processing, to pick only those symbols (e.g. func, class, ...)
   from the public API, that are relevant for that section.

3. Once we have our classes / functions, etc, we generate the mkdocstring entries like
   so:

   ```md
   ::: my_library.my_module.my_class
   ```

   See https://mkdocstrings.github.io/

4. These generated files in `docs/reference` are then picked up by mkdocs / mkdocstrings
   when we build or serve mkdocs, e.g. with:

    ```sh
    mkdocs serve
    ```

Note that this file is set in the `gen-files` plugin in `mkdocs.yml`. That means that
we don't have to run it manually. It will be run each time mkdocs is built.
"""

import inspect
import re
import sys
from importlib import import_module
from pathlib import Path
from textwrap import dedent
from typing import Any, NamedTuple

import mkdocs_gen_files
from django.conf import settings

from django_components import Component, ComponentVars
from django_components.node import BaseNode
from django_components.util.misc import get_import_path

# NOTE: This file is an entrypoint for the `gen-files` plugin in `mkdocs.yml`.
#       However, `gen-files` plugin runs this file as a script, NOT as a module.
#       That means that:
#         - By default we can't do relative imports (e.g. `.extensions`)
#         - We can't import from packages found in the `src` directory (e.g. `docs.scripts.extensions`)
#
#       But we need to import from another module in ./docs/scripts.
#       Hence we add the directory of this file to `sys.path` ourselves.

current_dir = str(Path(__file__).parent)
sys.path.append(current_dir)
from extensions import _format_source_code_html

root = Path(__file__).parent.parent.parent


def gen_reference_api() -> None:
    """
    Generate documentation for the Python API of `django_components`.

    This takes all public symbols exported from `django_components`, except for those
    that are handled in other sections, like components, exceptions, etc.
    """
    module = import_module("django_components")

    preface = "<!-- Autogenerated by reference.py -->\n\n"
    template_path = "docs/templates/reference_api.md"
    preface += (root / template_path).read_text()
    out_path = "reference/api.md"

    with mkdocs_gen_files.open(out_path, "w", encoding="utf-8") as f:
        f.write(preface + "\n\n")

        for name, obj in inspect.getmembers(module):
            if (
                name.startswith("_")
                or inspect.ismodule(obj)
                # Skip entries which are handled in other sections
                or _is_component_cls(obj)
                or _is_error_cls(obj)
            ):
                continue

            # For each entry, generate a mkdocstrings entry, e.g.
            # ```
            # ::: django_components.Component
            #     options:
            #       show_if_no_docstring: true
            # ```
            f.write(f"::: {module.__name__}.{name}\n    options:\n      show_if_no_docstring: true\n")

            f.write("\n")

    mkdocs_gen_files.set_edit_path(out_path, template_path)


def gen_reference_testing_api() -> None:
    """
    Generate documentation for the Python API of `django_components.testing`.

    This takes all public symbols exported from `django_components.testing`.
    """
    module = import_module("django_components.testing")

    preface = "<!-- Autogenerated by reference.py -->\n\n"
    template_path = "docs/templates/reference_testing_api.md"
    preface += (root / template_path).read_text()
    out_path = "reference/testing_api.md"

    with mkdocs_gen_files.open(out_path, "w", encoding="utf-8") as f:
        f.write(preface + "\n\n")

        for name, obj in inspect.getmembers(module):
            if name.startswith("_") or inspect.ismodule(obj):
                continue

            # For each entry, generate a mkdocstrings entry, e.g.
            # ```
            # ::: django_components.testing.djc_test
            #     options:
            #       show_if_no_docstring: true
            # ```
            f.write(f"::: {module.__name__}.{name}\n    options:\n      show_if_no_docstring: true\n")

            f.write("\n")

    mkdocs_gen_files.set_edit_path(out_path, template_path)


def gen_reference_exceptions() -> None:
    """Generate documentation for the Exception classes included in the Python API of `django_components`."""
    module = import_module("django_components")

    preface = "<!-- Autogenerated by reference.py -->\n\n"
    template_path = "docs/templates/reference_exceptions.md"
    preface += (root / template_path).read_text()
    out_path = "reference/exceptions.md"

    with mkdocs_gen_files.open(out_path, "w", encoding="utf-8") as f:
        f.write(preface + "\n\n")

        for name, obj in inspect.getmembers(module):
            if (
                name.startswith("_")
                or inspect.ismodule(obj)
                # Skip entries which are handled in other sections
                or not _is_error_cls(obj)
            ):
                continue

            # For each entry, generate a mkdocstrings entry, e.g.
            # ```
            # ::: django_components.Component
            #     options:
            #       show_if_no_docstring: true
            # ```
            f.write(f"::: {module.__name__}.{name}\n    options:\n      show_if_no_docstring: true\n")

            f.write("\n")

    mkdocs_gen_files.set_edit_path(out_path, template_path)


def gen_reference_settings() -> None:
    """Generate documentation for the settings of django-components, as defined by the `ComponentsSettings` class."""
    module = import_module("django_components.app_settings")

    preface = "<!-- Autogenerated by reference.py -->\n\n"
    template_path = "docs/templates/reference_settings.md"
    preface += (root / template_path).read_text()
    out_path = "reference/settings.md"

    with mkdocs_gen_files.open(out_path, "w", encoding="utf-8") as f:
        # 1. Insert section from `reference_settings.md`
        f.write(preface + "\n\n")

        # 2. Insert code snippet with default settings from `app_settings.py`
        if not module.__file__:
            raise RuntimeError(f"Failed to get filepath for module '{module.__name__}'")

        default_settings_markdown = _gen_default_settings_section(module.__file__)
        f.write(default_settings_markdown)

        # 3. Print each setting and their descriptions
        setting_cls = module.ComponentsSettings
        class_name = get_import_path(setting_cls)

        # NOTE: If no unique methods, just document the class itself without methods
        unique_methods = _get_unique_methods(NamedTuple, setting_cls)

        for name in sorted(unique_methods):
            # Ignore - these belong to NamedTuple
            if name in ("count", "index"):
                continue

            # For each entry, generate a mkdocstrings entry, e.g.
            # ```
            # ::: django_components.app_settings.ComponentsSettings.autodiscover
            #     options:
            #       ...
            # ```
            f.write(
                f"::: {class_name}.{name}\n"
                f"    options:\n"
                f"      show_root_heading: true\n"
                f"      show_signature: true\n"
                f"      separate_signature: true\n"
                f"      show_symbol_type_heading: false\n"
                f"      show_symbol_type_toc: false\n"
                f"      show_if_no_docstring: true\n"
                f"      show_labels: false\n",
            )
            f.write("\n")

    mkdocs_gen_files.set_edit_path(out_path, template_path)


# Get attributes / methods that are unique to the subclass
def _get_unique_methods(base_class: type, sub_class: type) -> list[str]:
    base_methods = set(dir(base_class))
    subclass_methods = set(dir(sub_class))
    unique_methods = subclass_methods - base_methods

    return [method for method in unique_methods if not method.startswith("_")]


def _gen_default_settings_section(app_settings_filepath: str) -> str:
    # In the source code (`app_settings.py`), we've inserted following strings
    # to mark the start and end of the where we define the default settings.
    # We copy this as a plain string, so that the comments are preserved.
    settings_sourcecode = Path(app_settings_filepath).read_text()
    defaults_snippet = settings_sourcecode.split("--snippet:defaults--")[1].split("--endsnippet:defaults--")[0]

    # Next we need to clean up the snippet:

    # Remove single line from both ends to remove comments and the snippet strings
    defaults_snippet_lines = defaults_snippet.split("\n")[1:-1]

    # Also remove escape/formatter comments at the end of the lines like
    # `# noqa` or `# type: ignore`
    comment_re = re.compile(r"#\s+(?:type\:|noqa)")

    # Some settings are dynamic in a sense that their value depends on the Django settings,
    # and thus may change anytime. Because the default settings are defined at the top-level
    # of the module, we want to delay evaluation of `settings.my_setting`. For that we use the
    # `Dynamic` class and a lambda function.
    #
    # However, for the documentation, we need to remove those.
    dynamic_re = re.compile(r"Dynamic\(lambda\: (?P<code>.+)\)")
    cleaned_snippet_lines: list[str] = []
    for line in defaults_snippet_lines:
        curr_line = comment_re.split(line)[0].rstrip()
        curr_line = dynamic_re.sub(
            lambda m: m.group("code"),
            curr_line,
        )
        cleaned_snippet_lines.append(curr_line)
    clean_defaults_snippet = "\n".join(cleaned_snippet_lines)

    return (
        "### Settings defaults\n\n"
        "Here's overview of all available settings and their defaults:\n\n"
        f"```py\n{clean_defaults_snippet}\n```"
        "\n\n"
    )


def gen_reference_template_tags() -> None:
    """
    Generate documentation for all Django template tags defined by django-components,
    like `{% slot %}`, `{% component %}`, etc.

    These are discovered by looking at the files defined inside `django_components/template_tags`.
    """
    tags_files = Path("./src/django_components/templatetags").glob("*.py")
    tags_modules = [
        (p.stem, f"django_components.templatetags.{p.stem}") for p in tags_files if not p.stem.startswith("_")
    ]

    preface = "<!-- Autogenerated by reference.py -->\n\n"
    template_path = "docs/templates/reference_template_tags.md"
    preface += (root / template_path).read_text()
    out_path = "reference/template_tags.md"

    with mkdocs_gen_files.open(out_path, "w", encoding="utf-8") as f:
        f.write(preface + "\n\n")

        for mod_name, mod_path in tags_modules:
            tags_module = import_module(mod_path)
            module_rel_path = Path(tags_module.__file__).relative_to(Path.cwd()).as_posix()  # type: ignore[arg-type]

            f.write(
                f"All following template tags are defined in\n\n"
                f"`{mod_path}`\n\n"
                f"Import as\n```django\n{{% load {mod_name} %}}\n```\n\n",
            )

            for _, obj in inspect.getmembers(tags_module):
                if not _is_template_tag(obj):
                    continue

                node_cls: BaseNode = obj
                name = node_cls.tag
                tag_signature = _format_tag_signature(node_cls)
                obj_lineno = inspect.findsource(node_cls)[1]
                source_code_link = _format_source_code_html(module_rel_path, obj_lineno)

                # Use the tag's function's docstring
                docstring = dedent(node_cls.__doc__ or "").strip()

                # Rebuild (almost) the same documentation than as if we used
                # mkdocstrings' `::: path.to.module` syntax.
                # Instead we rebuild it, so we can format the function signature as template tag,
                # e.g.
                # ```django
                # {% component [arg, ...] **kwargs [only] %}
                # {% endcomponent %}
                # ```
                # fmt: off
                f.write(
                    f"## {name}\n\n"
                    f"```django\n"
                    f"{tag_signature}\n"
                    f"```\n\n"
                    f"{source_code_link}\n\n"
                    f"{docstring}\n\n",
                )
                # fmt: on

    mkdocs_gen_files.set_edit_path(out_path, template_path)


def gen_reference_template_variables() -> None:
    """
    Generate documentation for all variables that are available inside the component templates
    under the `{{ component_vars }}` variable, as defined by `ComponentVars`.
    """
    preface = "<!-- Autogenerated by reference.py -->\n\n"
    template_path = "docs/templates/reference_template_variables.md"
    preface += (root / template_path).read_text()
    out_path = "reference/template_variables.md"

    with mkdocs_gen_files.open(out_path, "w", encoding="utf-8") as f:
        f.write(preface + "\n\n")

        for field in ComponentVars._fields:
            f.write(f"::: {ComponentVars.__module__}.{ComponentVars.__name__}.{field}\n\n")

    mkdocs_gen_files.set_edit_path(out_path, template_path)


# NOTE: Unlike other references, the API of Signals is not yet codified (AKA source of truth defined
# as Python code). Instead, we manually list all signals that are sent by django-components.
def gen_reference_signals() -> None:
    """
    Generate documentation for all [Django Signals](https://docs.djangoproject.com/en/5.2/ref/signals) that are
    send by or during the use of django-components.
    """
    preface = "<!-- Autogenerated by reference.py -->\n\n"
    template_path = "docs/templates/reference_signals.md"
    preface += (root / template_path).read_text()
    out_path = "reference/signals.md"

    with mkdocs_gen_files.open(out_path, "w", encoding="utf-8") as f:
        f.write(preface + "\n\n")

    mkdocs_gen_files.set_edit_path(out_path, template_path)


def _format_tag_signature(node_cls: BaseNode) -> str:
    """
    Given the Node class, format the tag's function signature like:
    ```django
    {% component arg1: int, arg2: str, *args, **kwargs: Any [only] %}
    {% endcomponent %}
    ```
    """
    # The signature returns a string like:
    # `(arg: Any, **kwargs: Any) -> None`
    params_str = str(node_cls._signature)
    # Remove the return type annotation, the `-> None` part
    params_str = params_str.rsplit("->", 1)[0]
    # Remove brackets around the params, to end up only with `arg: Any, **kwargs: Any`
    params_str = params_str.strip()[1:-1]

    if node_cls.allowed_flags:
        params_str += " " + " ".join([f"[{name}]" for name in node_cls.allowed_flags])

    # Create the function signature
    full_tag = "{% " + node_cls.tag + " " + params_str + " %}"
    if node_cls.end_tag:
        full_tag += f"\n{{% {node_cls.end_tag} %}}"

    return full_tag


def _is_component_cls(obj: Any) -> bool:
    return inspect.isclass(obj) and issubclass(obj, Component) and obj is not Component


def _is_error_cls(obj: Any) -> bool:
    return inspect.isclass(obj) and issubclass(obj, Exception) and obj is not Exception


def _is_template_tag(obj: Any) -> bool:
    return inspect.isclass(obj) and issubclass(obj, BaseNode)


def gen_reference() -> None:
    """The entrypoint to generate all the reference documentation."""
    # Set up Django settings so we can import `extensions`
    if not settings.configured:
        settings.configure(
            BASE_DIR=Path(__file__).parent.parent.parent,
        )

    gen_reference_api()
    gen_reference_exceptions()
    gen_reference_settings()
    gen_reference_template_tags()
    gen_reference_template_variables()
    gen_reference_signals()
    gen_reference_testing_api()


# This is run when `gen-files` plugin is run in mkdocs.yml
if __name__ == "__main__":
    gen_reference()
