# `.nav.yml` is provided by https://lukasgeiter.github.io/mkdocs-awesome-nav
nav:
  - Single-file components: single_file_components.md
  - HTML / JS / CSS files: html_js_css_files.md
  - Render API: render_api.md
  - Rendering components: rendering_components.md
  - Slots: slots.md
  - Template tag syntax: template_tag_syntax.md
  - HTML attributes: html_attributes.md
  - HTTP Request: http_request.md
  - Subclassing components: subclassing_components.md
  - Autodiscovery: autodiscovery.md
